"""
test_adversarial_m3_stress.py - Milestone 3 Adversarial Stress & Chaos Test Suite

Adversarially attacks and stress-tests:
1. Pydantic schema validation boundaries, invalid types, duration constraints, extra fields.
2. Direct AST parsing and validation of CLI argument compatibility between remote_trigger.py and orchestrator.py.
3. Tasker XML structural invariant testing and mutation robustness.
4. Zeroconf DiscoveredADBService socket validation, endpoint properties, and extract_ip_address logic.
5. Exhaustive Blueprint Section 8.1 Edge Cases 1-23 validation.
"""

from datetime import datetime
import json
import os
from pathlib import Path
import re
import socket
import sys
import unittest
from unittest.mock import MagicMock
import xml.etree.ElementTree as ET
from pydantic import ValidationError

SCRIPT_DIR = Path(__file__).resolve().parent
MODULE_DIR = SCRIPT_DIR.parent
if str(MODULE_DIR) not in sys.path:
    sys.path.insert(0, str(MODULE_DIR))

from config import (
    BrandType,
    EventTier,
    MDNS_ADB_TLS_SERVICE_TYPE,
    MDNS_ADB_LEGACY_SERVICE_TYPE,
    ReframeMode,
)
from remote_trigger import (
    PipelineTriggerRequest,
    TriggerResponse,
    ConflictResponse,
    build_orchestrator_command,
)
from orchestrator import build_parser
from samsung_ingest import DiscoveredADBService, extract_ip_address


class TestPydanticSchemaAdversarialBoundaries(unittest.TestCase):
    """Stress-tests PipelineTriggerRequest with out-of-bound inputs, malformed types, and edge cases."""

    def test_duration_boundary_constraints(self):
        """Tests duration constraints: min 5.0s, max 59.0s."""
        # 1. Valid lower boundary (5.0s)
        req_min = PipelineTriggerRequest(drop_duration=5.0)
        self.assertEqual(req_min.drop_duration, 5.0)

        # 2. Valid upper boundary (59.0s)
        req_max = PipelineTriggerRequest(drop_duration=59.0)
        self.assertEqual(req_max.drop_duration, 59.0)

        # 3. Below minimum (<5.0s) must raise ValidationError
        with self.assertRaises(ValidationError):
            PipelineTriggerRequest(drop_duration=4.9)

        # 4. Above maximum (>59.0s) must raise ValidationError
        with self.assertRaises(ValidationError):
            PipelineTriggerRequest(drop_duration=59.1)

    def test_extra_arbitrary_fields_permitted(self):
        """Tests that extra fields sent by legacy or third-party webhooks (e.g. 'source', 'custom_tag') are accepted."""
        payload = {
            "source": "s26_ultra_knox",
            "custom_tag": "vip_tent",
            "event": "EDCLasVegas",
            "artist": "SubFocus",
            "from_device": True,
            "auto_drop": True,
        }
        req = PipelineTriggerRequest(**payload)
        self.assertEqual(req.event, "EDCLasVegas")
        self.assertEqual(getattr(req, "source", None), "s26_ultra_knox")

    def test_poll_timeout_validation(self):
        """Tests poll_timeout minimum bound (10.0s)."""
        req = PipelineTriggerRequest(poll_timeout=15.0)
        self.assertEqual(req.poll_timeout, 15.0)

        with self.assertRaises(ValidationError):
            PipelineTriggerRequest(poll_timeout=5.0)


class TestRemoteTriggerOrchestratorCLIAlignment(unittest.TestCase):
    """Tests that commands generated by remote_trigger.py are 100% accepted and valid for orchestrator.py."""

    def setUp(self):
        self.parser = build_parser()

    def test_cli_argument_roundtrip_compatibility(self):
        """Generates CLI command from PipelineTriggerRequest and asserts orchestrator.py parser accepts all args."""
        test_cases = [
            # Case 1: Default from-device auto-drop
            PipelineTriggerRequest(
                event="UltraMiami",
                artist="MartinGarrix",
                track="Animals",
                genre="mainstage",
                brand="laser_baptism",
                tier="pillar_a_stadium_arena",
                from_device=True,
                auto_drop=True,
                drop_duration=28.5,
                publish_youtube=False,
                dry_run=True,
            ),
            # Case 2: Specific device serial with YouTube publishing
            PipelineTriggerRequest(
                event="Tomorrowland",
                artist="Hardwell",
                track="Spaceman",
                genre="bigroom",
                brand="laser_baptism",
                tier="pillar_c_festival_mega",
                from_device=True,
                device_serial="R5CX10ABCDE",
                auto_drop=True,
                drop_duration=30.0,
                publish_youtube=True,
                auto_promote=True,
                dry_run=True,
            ),
            # Case 3: Explicit input file with manual start time
            PipelineTriggerRequest(
                event="ClubSpace",
                artist="JohnSummit",
                track="WhereYouAre",
                genre="tech_house",
                brand="music_baptism",
                tier="pillar_b_club_spotlight",
                from_device=False,
                input_file="01_RAW_INBOX/take1.mp4",
                auto_drop=False,
                start_time=12.0,
                duration=35.0,
                reframe_mode="blur_pad",
                publish_youtube=False,
                dry_run=True,
            ),
        ]

        for i, req in enumerate(test_cases):
            cmd_list = build_orchestrator_command(req, workspace_root=MODULE_DIR)
            self.assertTrue(len(cmd_list) >= 4)
            # Find the index of the subcommand 'pipeline'
            subcmd_idx = cmd_list.index("pipeline")
            pipeline_args = cmd_list[subcmd_idx:]

            # Pass arguments into orchestrator.py argument parser
            parsed = self.parser.parse_args(pipeline_args)
            self.assertEqual(parsed.subcommand, "pipeline", f"Case {i} failed subcommand check")
            self.assertEqual(parsed.event, req.event, f"Case {i} failed event check")
            self.assertEqual(parsed.artist, req.artist, f"Case {i} failed artist check")
            self.assertEqual(parsed.track, req.track, f"Case {i} failed track check")
            self.assertEqual(parsed.dry_run, req.dry_run, f"Case {i} failed dry_run check")


class TestTaskerXMLStructureAndFaultTolerance(unittest.TestCase):
    """Stress-tests Tasker XML configuration for schema integrity and error tolerance."""

    def setUp(self):
        self.tasker_path = MODULE_DIR / "tasker_profile.md"
        self.tasker_text = self.tasker_path.read_text(encoding="utf-8")

    def test_tasker_xml_continue_on_error_enforcement(self):
        """Asserts that Action 339 has <Int sr='arg11' val='1'/> to prevent unhandled crash on network drop."""
        xml_matches = re.findall(r"<TaskerData[\s\S]*?</TaskerData>", self.tasker_text)
        self.assertGreaterEqual(len(xml_matches), 1)

        for xml_str in xml_matches:
            root = ET.fromstring(xml_str)
            tasks = root.findall(".//Task")
            for task in tasks:
                actions = task.findall("Action")
                http_acts = [act for act in actions if act.find("code").text == "339"]
                self.assertEqual(len(http_acts), 1, "Expected exactly 1 HTTP Request action")
                http_act = http_acts[0]
                arg11 = http_act.find("Int[@sr='arg11']")
                self.assertIsNotNone(arg11, "Action 339 must have arg11 defined")
                self.assertEqual(arg11.attrib["val"], "1", "Action 339 arg11 must be 1 (Continue Task After Error)")

    def test_tasker_xml_both_branches_terminate_in_end_if(self):
        """Asserts that If (code 37) and Else (code 43) are properly closed by End If (code 38)."""
        xml_matches = re.findall(r"<TaskerData[\s\S]*?</TaskerData>", self.tasker_text)
        for xml_str in xml_matches:
            root = ET.fromstring(xml_str)
            tasks = root.findall(".//Task")
            for task in tasks:
                codes = [act.find("code").text for act in task.findall("Action")]
                self.assertIn("37", codes, "If action code 37 missing")
                self.assertIn("43", codes, "Else action code 43 missing")
                self.assertIn("38", codes, "End If action code 38 missing")

                if_idx = codes.index("37")
                else_idx = codes.index("43")
                endif_idx = codes.index("38")

                self.assertTrue(if_idx < else_idx < endif_idx, "Condition branch order must be If -> Else -> End If")


class TestZeroconfDiscoveredServiceAdversarial(unittest.TestCase):
    """Tests DiscoveredADBService dataclass and socket address parsing."""

    def test_discovered_service_properties(self):
        """Tests valid IPv4 endpoint construction and Samsung/S26 detection."""
        svc = DiscoveredADBService(
            name="adb-SM-S948U-xyz._adb-tls-connect._tcp.local.",
            service_type="_adb-tls-connect._tcp.local.",
            ip_address="192.168.1.150",
            port=42109,
            server="SM-S948U.local.",
            properties={"model": "SM-S948U"},
        )
        self.assertEqual(svc.endpoint, "192.168.1.150:42109")
        self.assertEqual(svc.model, "SM-S948U")
        self.assertTrue(svc.is_samsung)
        self.assertTrue(svc.is_s26_ultra)

    def test_extract_ip_address_raw_bytes_and_parsed(self):
        """Tests IP extraction from raw 4-byte socket addresses."""
        mock_info = MagicMock()
        mock_info.parsed_addresses.return_value = ["192.168.1.188"]
        ip = extract_ip_address(mock_info)
        self.assertEqual(ip, "192.168.1.188")

        mock_info2 = MagicMock()
        mock_info2.parsed_addresses = None
        mock_info2.addresses = [socket.inet_aton("10.0.0.45")]
        ip2 = extract_ip_address(mock_info2)
        self.assertEqual(ip2, "10.0.0.45")


class TestBlueprintExhaustiveEdgeCases(unittest.TestCase):
    """Exhaustively verifies Edge Cases 1 through 23 in Section 8.1 of the Blueprint."""

    def setUp(self):
        self.bp_path = MODULE_DIR / "V2_CONSOLIDATED_EDM_SHORT_FORM_BLUEPRINT.md"
        self.bp_text = self.bp_path.read_text(encoding="utf-8")

    def test_all_23_edge_cases_present(self):
        """Asserts all 23 edge cases exist sequentially in the remediation matrix."""
        for i in range(1, 24):
            pattern = re.compile(rf"\|\s*{i}\s*\|\s*\*\*([^*]+)\*\*", re.MULTILINE)
            match = pattern.search(self.bp_text)
            self.assertIsNotNone(match, f"Edge case #{i} missing from Section 8.1 table")


if __name__ == "__main__":
    unittest.main()
