-- =============================================================================
-- Quick Share AI Loop PostgreSQL Database Schema
-- Target: Google Cloud SQL for PostgreSQL / Local PostgreSQL 14+
-- =============================================================================

CREATE TABLE IF NOT EXISTS video_tags (
    id BIGSERIAL PRIMARY KEY,
    filename VARCHAR(512) NOT NULL UNIQUE,
    filepath TEXT NOT NULL,
    domain VARCHAR(100) NOT NULL DEFAULT 'Unknown',
    entity VARCHAR(255) NOT NULL DEFAULT 'Unknown',
    viral_features JSONB NOT NULL DEFAULT '[]'::jsonb,
    technical JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Documentation Comments
COMMENT ON TABLE video_tags IS 'Video tagging metadata generated by Gemini 3.6 Flash multimodal AI inference.';
COMMENT ON COLUMN video_tags.id IS 'Synthetic unique primary key identifier.';
COMMENT ON COLUMN video_tags.filename IS 'Unique base filename of the ingested video media.';
COMMENT ON COLUMN video_tags.filepath IS 'Original or Google Drive ingested absolute path of the video.';
COMMENT ON COLUMN video_tags.domain IS 'High-level taxonomy category (e.g., EDM, Sports Cards, Travel).';
COMMENT ON COLUMN video_tags.entity IS 'Specific subject entity (e.g., Excision, Victor Wembanyama).';
COMMENT ON COLUMN video_tags.viral_features IS 'JSONB array of strings detailing viral hooks (e.g., ["Heavy_Lasers", "Bass_Drop_0:15"]).';
COMMENT ON COLUMN video_tags.technical IS 'JSONB object containing video quality, resolution, audio clipping, and capture metrics.';
COMMENT ON COLUMN video_tags.created_at IS 'UTC timestamp when record was initially created.';
COMMENT ON COLUMN video_tags.updated_at IS 'UTC timestamp when record was last updated.';

-- Indexes for Fast Querying and JSON Containment
CREATE UNIQUE INDEX IF NOT EXISTS idx_video_tags_filename ON video_tags (filename);
CREATE INDEX IF NOT EXISTS idx_video_tags_domain ON video_tags (domain);
CREATE INDEX IF NOT EXISTS idx_video_tags_entity ON video_tags (entity);
CREATE INDEX IF NOT EXISTS idx_video_tags_domain_entity ON video_tags (domain, entity);
CREATE INDEX IF NOT EXISTS idx_video_tags_viral_features_gin ON video_tags USING GIN (viral_features jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_video_tags_technical_gin ON video_tags USING GIN (technical);
CREATE INDEX IF NOT EXISTS idx_video_tags_created_at ON video_tags (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_video_tags_updated_at ON video_tags (updated_at DESC);
